CREATE TABLE USERS (
USER_ID SERIAL PRIMARY KEY,
USER_NAME VARCHAR(256) NOT NULL,
EMAIL VARCHAR(256) NOT NULL,
PHONE INTEGER NOT NULL,
PASSWORD VARCHAR(16) NOT NULL,
POINTS INTEGER DEFAULT 500,
ADDRESS VARCHAR(256),
DATE_JOINED DATE
);

CREATE TABLE PRODUCTS (
PRODUCT_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(256) NOT NULL,
DESCRIPTION TEXT,
OWNER_ID INTEGER REFERENCES USERS(USER_ID),
IS_AVAILABLE BOOLEAN
);

CREATE TABLE AUCTIONS (
AUCTION_ID SERIAL PRIMARY KEY,
START_TIME_AVAIL DATE NOT NULL,
END_TIME_AVAIL DATE,
PICK_UP VARCHAR(1000),
MIN_PRICE INTEGER NOT NULL,
CONDI VARCHAR(64),
TIME_CREATED DATE,
TIME_ENDED DATE,
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
STATUS BOOLEAN
);

CREATE TABLE BIDS (
BID_ID SERIAL PRIMARY KEY,
AUCTIONS INTEGER REFERENCES AUCTIONS(AUCTION_ID),
BIDDER_ID INTEGER REFERENCES USERS(USER_ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
POINTS INTEGER NOT NULL,
TIME_CREATED DATE,
BORROW_TIME DATE,
RETURN_TIME DATE,
PICKUP VARCHAR(256)
);

CREATE TABLE LOANS (
BID_ID INTEGER REFERENCES BIDS(BID_ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
RETURNED_TIME DATE,
IS_RETURNED BOOLEAN,
PRIMARY KEY (BID_ID,PRODUCT_ID)
);
