CREATE TABLE USERS (
USER_ID SERIAL PRIMARY KEY,
USER_NAME VARCHAR(256) NOT NULL,
EMAIL VARCHAR(256) NOT NULL,
PHONE INTEGER NOT NULL,
PASSWORD VARCHAR(16) NOT NULL,
POINTS INTEGER DEFAULT 500,
ADDRESS VARCHAR(256),
DATE_JOINED DATE,
ADMIN BOOLEAN
);

CREATE TABLE PRODUCTS (
PRODUCT_ID SERIAL PRIMARY KEY,
TITLE VARCHAR(256) NOT NULL,
CATE VARCHAR(64) CHECK(CATE In ('Tool', 'Appliance', 'Furniture', 'Book')),
DESCRIPTION TEXT,
OWNER_ID INTEGER REFERENCES USERS(USER_ID),
IS_AVAILABLE BOOLEAN,
PIC VARCHAR(1000)
);

CREATE TABLE AUCTIONS (
AUCTION_ID SERIAL PRIMARY KEY,
START_TIME_AVAIL DATE NOT NULL,
END_TIME_AVAIL DATE,
PICK_UP VARCHAR(1000),
MIN_PRICE INTEGER NOT NULL,
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
STATUS BOOLEAN
);

CREATE TABLE BIDS (
BID_ID SERIAL PRIMARY KEY,
AUCTIONS INTEGER REFERENCES AUCTIONS(AUCTION_ID),
BIDDER_ID INTEGER REFERENCES USERS(USER_ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
POINTS INTEGER NOT NULL,
TIME_CREATED DATETIME,
BORROW_TIME DATE,
RETURN_TIME DATE,
PICKUP VARCHAR(256),
STATUS VARCHAR(10) CHECK(STATUS In ('Pending','Success','Failure'))
);

CREATE TABLE LOANS (
BID_ID INTEGER REFERENCES BIDS(BID_ID),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(PRODUCT_ID),
RETURNED_TIME DATE,
IS_RETURNED BOOLEAN,
PRIMARY KEY (BID_ID,PRODUCT_ID)
);
